**Задание 1.**

In [2]:
import numpy as np

In [9]:
n = int(input('Enter N:'))
np.arange(n)[::-1]

Enter N:10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**Задание 2.**

In [11]:
x = int(input('Enter N:'))
y = np.diag(np.arange(x)[::-1], k=0)
print(y)

Enter N:5
[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [19]:
total_sum = 0
for elem in y.flat:
    if elem != 0:
        total_sum += elem
print(total_sum)

10


**Задание 3**

In [4]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [5]:
b = np.array( [4, 12, -3] )

In [6]:
from numpy import linalg

In [7]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [8]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True